version: '3'
services:
  front:
    command: ["nginx", "-g", "daemon off;"]
    build:
      context: ./angular-client
      dockerfile: Dockerfile
    container_name: photo-storage-front
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 80:80
    image: "photo-storage-front:latest"
    restart: always

  api:
    build:
      context: ./photo-storage-backend
      dockerfile: Dockerfile
    container_name: photo-storage-backend
    depends_on:
      - mysql
    env_file:
      - configuration.env
    volumes:
      - ~/.photos:/maps
      - ~/.thumbnail:/thumbnails
    image: "photo-storage-backend:latest"
    ports:
      - 8080:8080
    restart: always

  mysql:
    container_name: mysql-for-cyview
    image: mysql/mysql-server:5.7
    env_file:
      - configuration.env
    ports:
      - "3333:3306"
    restart: always
    volumes:
      - ~/.photo-storage-data:/var/lib/mysql
