spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
  jpa:
    show-sql: false
  servlet:
    multipart:
      enabled: false
logging:
  level:
    org.springframework.security: info
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create