spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CYVIEW_MONOLITHIC
    username: root
    password: root
    platform: mysql
    initialize: false
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  http:
    multipart:
      enabled: false
security:
  ignored:
    - "*.bundle.*"
logging:
  level:
    org.springframework.security: info
